### PR TITLE
Get rid of cpufreqnextgovernor script and do its work in cpupower.c

### PR DESCRIPTION
**Pull request by tomaszg7**
Hi, some time ago, unaware of your work here I ported gkrellm2-cpufreq plugin to cpupower on my own. In the process I realized that using external script to chose next governor is not the best way. It complicates the code without need (as far as I could understand) while it is quite simple to do the work inside C code. It may not be very elegant but it works :)

### CODE REVIEW

**Comment by tomaszg7** [comment]
BTW. Is there a reason you based your port on 0.6.1 and not the most recent 0.6.4?

**Comment by sainsaar** [comment]
I think I chose gkrellm-cpufreq-0.6.1 as the base because it was conveniently in the Gentoo repository and I was already used to it. 0.6.2 brought along a new layout; I can't remember how much I tried it.

**Comment by sainsaar** [comment]
I'll test your pull request when I have time, probably in a week or two. One problem I see already is that the sudoers file allows only "/usr/bin/cpupower [...] -g userspace", but the C code now can call it with other governors.

**Comment by tomaszg7** [comment]
The only changes in newer version is to the "coupled" mode. I never used it, so I didn't notice any apparent change. 

I see the problem with sudoers entry. I forgot to copy it over correctly from my own local branch. I'll update PR.

**Comment by sainsaar** [comment]
Thanks! One more thing to check: is the sudoers file parsed in "C" locale or may there be others? In Estonian, for example, "[a-z]" excludes the end of alphabet from "ž" and "t" onwards.

**Comment by tomaszg7** [comment]
Curious, I was not aware of this behaviour.

Apparently you can set any locale for sudoers file:

```
 sudoers_locale    Locale to use when parsing the sudoers file, logging commands, and sending
                   email.  Note that changing the locale may affect how sudoers is interpreted.
                   Defaults to “C”.
```

Thus I replaced [a-z] with [[:lower:]] (escaping colon).

**Comment by tomaszg7** [comment]
Sorry to ping you, but did you check this PR?

**Comment by tomaszg7** [comment]
I've added a new commit to the PR that makes the plugin compatible with recent kernels/cpupower.

**Pull request merged**
